
RUT = 3
POLIZA = 4
AGENCIA = 5
UNIDAD = 6
RECIBO = 7
CUOTA = 8

# Directorio de archivos de entrada XLSX
PATH_ARCHIVOS = {'ENTRADA_CSV': 'INPUTS/', 'SALIDA_TXT': 'OUTPUTS/'}

COLUMNAS_ENCABEZADO = {'CRR': 0, 'VARIABLE_ICOM': 1, 'VALOR_VARIABLE': 2, 'RUT': RUT, 'POLIZA': POLIZA, 'AGENCIA': AGENCIA, 'UNIDAD': UNIDAD, 'RECIBO': RECIBO, 'CUOTA': CUOTA}

AGENTE_CONFIG = {
    'PK': {'RUT': RUT},
    'DIMENCION': {'RUT': RUT, 'AGENCIA': AGENCIA, 'UNIDAD': UNIDAD},
}

CODIGOS_GAGU_CONFIG = {
    'PK': {'RUT': RUT, 'AGENCIA': AGENCIA, 'UNIDAD': UNIDAD},
    'DIMENCION': {'RUT': RUT, 'AGENCIA': AGENCIA, 'UNIDAD': UNIDAD},
}

CUOTA_CONFIG = {
    'PK': {'POLIZA': POLIZA, 'RECIBO': RECIBO, 'CUOTA': CUOTA},
    'DIMENCION': {'POLIZA': POLIZA, 'RECIBO': RECIBO, 'CUOTA': CUOTA},
}

POLIZA_CONFIG = {
    'PK': {'POLIZA': POLIZA},
    'DIMENCION': {'RUT': RUT, 'POLIZA': POLIZA, 'UNIDAD': UNIDAD, 'AGENCIA': AGENCIA,},
}